version: "3.9"

services:
  rb_sensors-api:
    container_name: raspberry_sensors-api
    depends_on:
      - rb_sensors-db
    image: raspberry/sensors:v1.0.0
    restart: unless-stopped
    env_file:
      - ${PWD}/raspberry.env
    ports:
      - "3000:3000"
    networks:
      - rb_sensors-net

  rb_sensors-db:
    container_name: raspberry_sensors-db
    image: timescale/timescaledb:latest-pg12
    restart: unless-stopped
    volumes:
      - ${PWD}/timescale:/var/lib/postgresql/data/
    env_file:
      - ${PWD}/timescale.env
    ports:
      - "5432:5432"
    networks:
      - rb_sensors-net

networks:
  rb_sensors-net:
