version: "3.9"

services:
  rb_sensors-api:
    container_name: raspberry_sensors-api
    image: raspberry/sensors:v1.0.0
    restart: unless-stopped
    env_file:
      - ${PWD}/.env
    ports:
      - "3000:3000"
    networks:
      - rb_sensors-net

networks:
  rb_sensors-net:
